apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: endrha-com-tls
spec:
  secretName: endrha-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: endrha.com
  dnsNames:
    - endrha.com
    - www.endrha.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - endrha.com
          - www.endrha.com